/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#53442e",
        "tertiary-fixed-dim": "#d9c3a5",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "surface-tint": "#4a607c",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "inverse-primary": "#b2c8e8",
        "on-tertiary-fixed": "#251a07",
        "primary-fixed-dim": "#b2c8e8",
        "primary-container": "#0f2740",
        "on-primary-fixed": "#031c35",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#d2e4ff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c4c6ce",
        "error-container": "#ffdad6",
        "on-secondary-container": "#456d57",
        "outline": "#74777e",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "primary": "#001226",
        "surface": "#f7f9fb",
        "on-secondary-fixed-variant": "#274e3b",
        "surface-dim": "#d8dadc",
        "secondary-fixed": "#c0edd2",
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#798fad",
        "background": "#f7f9fb",
        "on-surface-variant": "#43474d",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#9d8a6f",
        "on-primary-fixed-variant": "#324863",
        "surface-container-highest": "#e0e3e5",
        "tertiary": "#1a0f01",
        "secondary": "#3f6752",
        "secondary-container": "#c0edd2",
        "tertiary-fixed": "#f6dfc0",
        "tertiary-container": "#302410",
        "secondary-fixed-dim": "#a5d0b7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1440px",
        "gutter": "32px",
        "unit": "8px",
        "section-gap": "120px",
        "margin-tablet": "40px",
        "margin-desktop": "80px"
      },
      fontFamily: {
        "headline-lg-mobile": ["manrope"],
        "label-sm": ["inter"],
        "headline-lg": ["manrope"],
        "body-lg": ["inter"],
        "body-md": ["inter"],
        "headline-md": ["manrope"],
        "display-xl": ["manrope"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
